### ISSUE TITLE
Exporting only 0byte .jsx files

### ISSUE THREAD

**Issue by jacobjc** [NTProductions/ae-mask-exporter#1]
Testing with AE 2024 v24.6.3 (also problem in other recent versions) - Windows 10 Pro.

The exported .jsx mask file has no data in it, 0 bytes.

**Comment by NTProductions** [comment]
This is a 4 year old free script, you can feel free to modify it and debug to find your particular issue.

**Comment by jacobjc** [comment]
thanks
